### ISSUE TITLE
Website updates round 1

### ISSUE THREAD

**Issue by stevanlohja** [open-rpc/website#1]
The initial github pages website is up at https://open-rpc.github.io/open-rpc/
The Jekyll based site is on the gh-pages branch of the repository.
This issue is to list a round of needed updates. Feel free to participate. We'll get this site for the actual open-rpc.org domain in time.
- [ ] move users to Participate page
- [ ] ~~do we really need an email in the footer? alternatives?~~ Use Discord
- [ ] "how to participate" link on homepage is broken.
- [ ] add mock server

**Comment by shanejonas** [comment]
lets also add `mock-server`

**Comment by BelfordZ** [comment]
I refuse to setup email addresses for the open-rpc.org domain.

Refer everyone to etclabs discord
