### ISSUE TITLE
Directory Links

### ISSUE THREAD

**Issue by captainblood16** [open-rpc/website#23]
Do you mind if you put the forum link you're willing to discuss this(like discord/telegram chat) where we can ask something about this repo? Will be happy to join.

**Comment by shanejonas** [comment]
https://discord.gg/JbuWWR

**Comment by shanejonas** [comment]
related to #4

**Comment by shanejonas** [comment]
rel #25

**Comment by captainblood16** [comment]
oops, the link expired. Invite link without expiry is better.

**Comment by shanejonas** [comment]
theres a discord widget on the site now:

https://open-rpc.org

but also, here is non-expiring link:

https://discord.gg/rsQ4esV
